id: AC6734EC2
title: Prayer for the Long Life of Shechen Rabjam Rinpoche
type: translation
source_metadata:
  languages:
  - en
  - de
  - fr
  - it
  - pt
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.241162
  last_modified_at: 2022-03-01 01:34:51.241165
