id: AC6734EC2
title: Prayer for the Long Life of Jamyang Khyentse Chökyi Lodrö
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.239314
  last_modified_at: 2022-03-01 01:34:51.239317
