id: AC6734EC2
title: A Concise Feast Prayer
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.226985
  last_modified_at: 2022-03-01 01:34:51.227008
