id: AC6734EC2
title: Brief Offering Prayer to Gesar
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.234995
  last_modified_at: 2022-03-01 01:34:51.234998
