id: AC6734EC2
title: A Prayer To Padmasambhava
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.228887
  last_modified_at: 2022-03-01 01:34:51.228891
