id: AC6734EC2
title: 'Pacifying the Turmoil of the Mamos: A Concise Liturgy'
type: translation
source_metadata:
  languages:
  - en
  - zh
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:34:51.238343
  last_modified_at: 2022-03-01 01:34:51.238345
